### -->1. Given an array a = np.array([10, 20, 30, 40, 50]) and an indexing array i = np.array([0, 1, 3]) , use fancy indexing to extract elements and assign new values to them.

In [1]:
import numpy as np

In [3]:
# Extract elements using fancy indexing
a = np.array([10, 20, 30, 40, 50])
i = np.array([0, 1, 3])
extracted_elements = a[i]
print("Extracted elements:", extracted_elements)

Extracted elements: [10 20 40]


In [9]:
# Assign new values to the selected elements
new_values = np.array([15, 25, 35, 45, 55])
a = new_values
print("Array after assigning values:", a)

Array after assigning values: [15 25 35 45 55]


### -->2. Create 4*4 matrix and compute the sum of all elements, the sum of each column, and the sum of each row.

Matrix
[[ 1  2  3  4]
[ 5  6  7  8]
[ 9 10 11 12]
[13 14 15 16]]
Sum of all elements: 136
Sum of each column: [28 32 36 40]
Sum of each row: [10 26 42 58]


In [19]:

# Create a 4x4 matrix
m = np.array([
[ 1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]])

total_sum = np.sum(m)                      #Compute the sum of all elements
column_sum = np.sum(m, axis=0)            #Compute the sum of each column
row_sum = np.sum(m, axis=1)               #Compute the sum of each row
print("Matrix:", m)                         #Print the results
print("Sum of all elements:", total_sum),
print("Sum of each column:", column_sum),
print("Sum of each row:", row_sum)


Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of all elements: 136
Sum of each column: [28 32 36 40]
Sum of each row: [10 26 42 58]


### -->3.Given a 3-D array of shape (3, 4, 5), slice out a sub-array that, contains the last two rows and columns of the last two matrices.
   ]

In [27]:
array_3d = np.arange(60).reshape(3, 4, 5)                        #Create a 3-D array
print("Original array:", array_3d)   #Slice out the sub-array containing the last two rows and columns of the last two matrices
sub_array = array_3d[:, -2:, -2:]
print("Sub-array with the last two rows and columns of the last two matrices:", sub_array)

Original array: [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
Sub-array with the last two rows and columns of the last two matrices: [[[13 14]
  [18 19]]

 [[33 34]
  [38 39]]

 [[53 54]
  [58 59]]]
